USE `kinetic_plex`;

-- TERM CATEGORIES

INSERT INTO `term_categories` (`name`, `description`, `creation_time`, `last_modification_time`, `is_deleted`) VALUES
    ('Alfabeto', 'Dactilología y letras individuales del abecedario.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Números', 'Números del 0 al 100 y expresiones de cantidad.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Pronombres', 'Pronombres personales, posesivos y demostrativos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Días de la Semana', 'Lunes, martes, miércoles, jueves, viernes, sábado, domingo.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Meses del Año', 'De enero a diciembre.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Adjetivos', 'Palabras para calificar, describir o dar cualidades.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Saludos y Modales', 'Fórmulas de cortesía, presentaciones y despedidas.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Colores', 'Gama de colores básicos y compuestos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Familia', 'Miembros del núcleo familiar y parentescos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Medios de Transporte', 'Vehículos y formas de movilidad terrestre, aérea y marítima.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Medios de Comunicación', 'Televisión, radio, teléfono, correo e internet.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Verbos', 'Acciones, movimientos y estados.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Ropa', 'Prendas de vestir, calzado y accesorios.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Alimentos', 'Comida en general, platos y provisiones.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Elementos del Hogar', 'Muebles, electrodomésticos y objetos de la casa.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Bebidas', 'Agua, jugos, leche y líquidos para consumo.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Frutas', 'Diferentes tipos de frutas frescas.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Vegetales', 'Hortalizas, víveres y vegetales.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Carnes', 'Diferentes tipos de carnes, aves y cortes.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Animales', 'Animales domésticos, salvajes y de granja.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Insectos', 'Bichos y pequeños insectos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Partes del Cuerpo Humano', 'Anatomía, órganos y extremidades.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Lugares de la Comunidad', 'Hospitales, bancos, parques, calles e instituciones públicas.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Lugares de la Escuela', 'Aulas, biblioteca, dirección, áreas recreativas escolares.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Profesiones', 'Oficios, carreras universitarias y trabajos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Religión', 'Conceptos de fe, iglesia, denominaciones y espiritualidad.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Juegos', 'Actividades recreativas, juguetes y pasatiempos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Naturaleza', 'Medio ambiente, clima, accidentes geográficos y fenómenos naturales.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Deportes', 'Disciplinas deportivas, ejercicios y competiciones.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Arte y Cultura', 'Expresiones artísticas, música, pintura y tradiciones.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Tiempo y Clima', 'Condiciones meteorológicas y estaciones del año.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Antónimos', 'Palabras con significados opuestos o contrarios.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Sociedad', 'Términos cívicos, gobierno, economía y convivencia.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Plantas', 'Árboles, flores, arbustos y vegetación en general.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Herramientas', 'Instrumentos de trabajo manual, mecánico o de construcción.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Tecnología', 'Dispositivos, computadoras, software y electrónica.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Útiles de Aseo', 'Artículos de higiene personal, baño y limpieza.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Útiles de Clase', 'Lápices, cuadernos, mochilas y materiales escolares.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Provincias', 'Provincias, municipios y regiones geográficas de la República Dominicana.', CURRENT_TIMESTAMP, NULL, FALSE);