USE `kinetic_plex`;

-- TERM CATEGORIES

INSERT INTO `term_categories` (`name`, `description`, `creation_time`, `last_modification_time`, `is_deleted`) VALUES
    ('Alfabeto', 'Dactilología y letras individuales del abecedario.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Números', 'Números del 0 al 100 y expresiones de cantidad.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Pronombres', 'Pronombres personales, posesivos y demostrativos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Días de la Semana', 'Lunes, martes, miércoles, jueves, viernes, sábado, domingo.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Meses del Año', 'De enero a diciembre.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Adjetivos', 'Palabras para calificar, describir o dar cualidades.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Saludos y Modales', 'Fórmulas de cortesía, presentaciones y despedidas.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Colores', 'Gama de colores básicos y compuestos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Familia', 'Miembros del núcleo familiar y parentescos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Medios de Transporte', 'Vehículos y formas de movilidad terrestre, aérea y marítima.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Medios de Comunicación', 'Televisión, radio, teléfono, correo e internet.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Verbos', 'Acciones, movimientos y estados.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Ropa', 'Prendas de vestir, calzado y accesorios.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Alimentos', 'Comida en general, platos y provisiones.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Elementos del Hogar', 'Muebles, electrodomésticos y objetos de la casa.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Bebidas', 'Agua, jugos, leche y líquidos para consumo.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Frutas', 'Diferentes tipos de frutas frescas.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Vegetales', 'Hortalizas, víveres y vegetales.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Carnes', 'Diferentes tipos de carnes, aves y cortes.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Animales', 'Animales domésticos, salvajes y de granja.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Insectos', 'Bichos y pequeños insectos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Partes del Cuerpo Humano', 'Anatomía, órganos y extremidades.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Lugares de la Comunidad', 'Hospitales, bancos, parques, calles e instituciones públicas.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Lugares de la Escuela', 'Aulas, biblioteca, dirección, áreas recreativas escolares.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Profesiones', 'Oficios, carreras universitarias y trabajos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Religión', 'Conceptos de fe, iglesia, denominaciones y espiritualidad.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Juegos', 'Actividades recreativas, juguetes y pasatiempos.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Naturaleza', 'Medio ambiente, clima, accidentes geográficos y fenómenos naturales.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Deportes', 'Disciplinas deportivas, ejercicios y competiciones.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Arte y Cultura', 'Expresiones artísticas, música, pintura y tradiciones.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Tiempo y Clima', 'Condiciones meteorológicas y estaciones del año.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Antónimos', 'Palabras con significados opuestos o contrarios.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Sociedad', 'Términos cívicos, gobierno, economía y convivencia.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Plantas', 'Árboles, flores, arbustos y vegetación en general.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Herramientas', 'Instrumentos de trabajo manual, mecánico o de construcción.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Tecnología', 'Dispositivos, computadoras, software y electrónica.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Útiles de Aseo', 'Artículos de higiene personal, baño y limpieza.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Útiles de Clase', 'Lápices, cuadernos, mochilas y materiales escolares.', CURRENT_TIMESTAMP, NULL, FALSE),
    ('Provincias', 'Provincias, municipios y regiones geográficas de la República Dominicana.', CURRENT_TIMESTAMP, NULL, FALSE);

-- ANIMATIONS

INSERT INTO `animations` (`term_category_id`, `key`, `name`, `duration`, `description`, `creation_time`, `last_modification_time`, `is_deleted`) VALUES
    (1, UUID(), 'Animación letra A', 1000, 'Deletreo manual: A', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra B', 1000, 'Deletreo manual: B', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra C', 1000, 'Deletreo manual: C', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra D', 1000, 'Deletreo manual: D', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra E', 1000, 'Deletreo manual: E', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra F', 1000, 'Deletreo manual: F', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra G', 1000, 'Deletreo manual: G', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra H', 1000, 'Deletreo manual: H', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra I', 1000, 'Deletreo manual: I', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra J', 1000, 'Deletreo manual: J', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra K', 1000, 'Deletreo manual: K', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra L', 1000, 'Deletreo manual: L', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra M', 1000, 'Deletreo manual: M', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra N', 1000, 'Deletreo manual: N', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra Ñ', 1000, 'Deletreo manual: Ñ', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra O', 1000, 'Deletreo manual: O', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra P', 1000, 'Deletreo manual: P', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra Q', 1000, 'Deletreo manual: Q', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra R', 1000, 'Deletreo manual: R', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra S', 1000, 'Deletreo manual: S', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra T', 1000, 'Deletreo manual: T', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra U', 1000, 'Deletreo manual: U', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra V', 1000, 'Deletreo manual: V', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra W', 1000, 'Deletreo manual: W', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra X', 1000, 'Deletreo manual: X', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra Y', 1000, 'Deletreo manual: Y', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, UUID(), 'Animación letra Z', 1000, 'Deletreo manual: Z', CURRENT_TIMESTAMP, NULL, FALSE);

-- TERMS

INSERT INTO `terms` (`term_category_id`, `animation_id`, `text`, `creation_time`, `last_modification_time`, `is_deleted`) VALUES
    (1, 1, 'A', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 2, 'B', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 3, 'C', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 4, 'D', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 5, 'E', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 6, 'F', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 7, 'G', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 8, 'H', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 9, 'I', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 10, 'J', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 11, 'K', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 12, 'L', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 13, 'M', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 14, 'N', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 15, 'Ñ', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 16, 'O', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 17, 'P', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 18, 'Q', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 19, 'R', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 20, 'S', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 21, 'T', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 22, 'U', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 23, 'V', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 24, 'W', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 25, 'X', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 26, 'Y', CURRENT_TIMESTAMP, NULL, FALSE),
    (1, 27, 'Z', CURRENT_TIMESTAMP, NULL, FALSE);

