"""Inital

Revision ID: 408862294cbf
Revises: 
Create Date: 2026-08-15 15:48:24.379459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408862294cbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_modification_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_modification_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_category_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_modification_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['term_category_id'], ['term_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation_request_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_modification_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['translation_request_id'], ['translation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animations_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animation_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_modification_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['animation_id'], ['animations.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_category_id', sa.Integer(), nullable=False),
    sa.Column('animation_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_modification_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['animation_id'], ['animations.id'], ),
    sa.ForeignKeyConstraint(['term_category_id'], ['term_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terms')
    op.drop_table('animations_sequences')
    op.drop_table('sequences')
    op.drop_table('animations')
    op.drop_table('translation_requests')
    op.drop_table('term_categories')
    # ### end Alembic commands ###
